- name: nginx installation
  hosts: gcp
  become: True
  tasks:
    - name: install nginx
      package: 
        name: nginx 
        update_cache: yes
    - name: copy config
      copy: 
        src: files/nginx.conf
        dest: /etc/nginx/
   # - name: enable conf
    #  file:
     #   dest: /etc/nginx/sites-enabled/default
      #  src: /etc/nginx/sites-available/default
       # state: link
        #force: yes
    - name: copy index.hmtl
      template: 
        src: templates/index.html.j2 
        dest: /usr/share/nginx/html/index.html
        mode: '0644'
    - name: restart nginx
      service: 
        name: nginx 
        state: restarted