---
- hosts: all
  tasks:
    - name: Base installation
      package:
        name: "{{ item }}"
        state: present
      loop: 
        - zip
        - unzip
        - gzip
        - nano
      become: yes
      tags: install
#----------------------------------
    - name: Uninstallation
      package:
        name: "{{ item }}"
        state: absent
      loop:
        - unzip
        - nano
      become: yes
      tags: uninstall
